/// Flutter icons DecoNewsIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DecoNewsIcons
///      fonts:
///       - asset: fonts/DecoNewsIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class DecoNewsIcons {
  DecoNewsIcons._();

  static const _kFontFam = 'DecoNewsIcons';

  static const IconData about_icon = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData add_to_bookmark = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData categories_icon = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData comments = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData date = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData facebook = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData home_icon = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData instagram = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData twitter = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData youtube = const IconData(0xe809, fontFamily: _kFontFam);
}
